name: joystick
description: A joystick widget for your gallery apps.
version: 0.0.9
homepage: https://github.com/Enesbulu/joystick.git

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  